name: CI

on: [pull_request]

jobs:

  local:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install flex and bison
      run: sudo apt-get install flex -y && sudo apt-get install bison -y
    - name: Test
      run: ./test.sh
  
  golite-solutions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install flex and bison
      run: sudo apt-get install flex -y && sudo apt-get install bison -y
    - name: Test Solutions
      run: ./test-solution.sh
