name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: sudo apt-get install flex -y && sudo apt-get install bison -y && ./build.sh && ./test.sh
